version: "3.9"
services:
  zhsy53:                     # zhsy53
    container_name: zhsy53    # 容器名称
    image: zhsy53/stock2:Web
    build:                    # 镜像构建
      context: .              # Dockerfile 与 docker-compose.yml 的相对目录
      dockerfile: Dockerfile  # Dockerfile 文件名
    restart: always

    command:
      - "/opt/history/"
      - "true"

    environment:              # 坏境变量
      TZ: Asia/Shanghai

    network_mode: bridge

    ports:
      - 54380:80/tcp

    sysctls:
      - net.ipv4.tcp_ecn=1
      - net.ipv4.tcp_ecn_fallback=1
      - net.ipv4.tcp_dsack=1
      - net.ipv4.tcp_fack=1
      - net.ipv4.tcp_sack=1
      - net.ipv4.conf.all.rp_filter=1
      - net.ipv4.conf.default.rp_filter=1
      - net.ipv4.tcp_keepalive_intvl=15
      - net.ipv4.tcp_keepalive_probes=5
      - net.ipv4.tcp_keepalive_time=75
      - net.ipv4.tcp_fastopen=3
      - net.ipv4.tcp_moderate_rcvbuf=1
      - net.ipv4.tcp_mtu_probing=2
      - net.ipv4.tcp_syncookies=1
      - net.ipv4.tcp_timestamps=1
      - net.ipv4.tcp_window_scaling=1

    volumes:
      - /dev/shm/TDX/Day/:/opt/history/:ro
      - /etc/localtime:/etc/localtime:ro
